# Travis CI будет использовать язык java.
language: java
install: true

# Версия JDK для сборки проекта
jdk: oraclejdk11

services:
  - postgresql

addons:
  postgresql: "10"

os:
  - linux

dist: xenial

before_install:
  - psql -c 'create database chat;' -U postgres

# После выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# И отправлять на сервис https://codecov.io/
after_success: bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN="6a334783-0d31-4692-b957-58c5ab6e5262"